
FROM node:19-alpine3.16 as build

RUN mkdir app

WORKDIR /app

COPY . . 

RUN yarn config set registry https://registry.npm.taobao.org/

RUN yarn install && yarn build

FROM ubuntu/nginx

COPY --from=build /app/build/ /var/www/html

EXPOSE 80

# COPY --from=build /app/nginx.conf /etc/nginx/conf.d/default.conf

ENTRYPOINT ["nginx", "-g", "daemon off;"]
